---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(infer)
library(janitor)
library(here)
```

```{r}
ames <- read_csv(here("data/ames.csv")) %>% 
  clean_names()
```

```{r}
ames %>% 
  ggplot() +
  aes(x = lot_area) +
  geom_histogram(colour = "white", bins = 60)
```
The distribution is heavily right skewed and has a very low standard deviation compared to the range. It's not  very normal.

```{r}
lot_area_bootstrap <- ames %>% 
  rep_sample_n(200, replace = TRUE, reps = 5000) %>% 
  summarise(
    mean_lot_area_bootstrap = mean(lot_area)
  )

lot_area_bootstrap %>% 
  ggplot() +
  aes(x = mean_lot_area_bootstrap) +
  geom_histogram(colour = "white")

```
```{r}
lot_area_resample <- ames %>%
  specify(response = lot_area) %>%
  generate(reps = 5000, type = "bootstrap") %>%
  calculate(stat = "mean")

lot_ci_95 <- lot_area_resample %>% 
  get_ci(level = 0.95, type = "percentile")

lot_area_resample %>% 
  visualise(bins = 30) +
  shade_confidence_interval(endpoints = lot_ci_95)


```

```{r}
lot_area_resample <- ames %>% 
  specify(response = lot_area) %>%
  generate(reps = 5000, type = "bootstrap") %>%
  calculate(stat = "mean")

lot_ci_99 <- lot_area_resample %>% 
  get_ci(level = 0.95, type = "percentile")

lot_area_resample %>% 
  visualise(bins = 30) +
  shade_confidence_interval(endpoints = lot_ci_99)


```
for a 99% CI, the field is narrower. This makes sense because youre cutting out more data you could be uncertain about.

```{r}
lot_area_resample %>% 
  summarise(point_mean = mean(stat))
```

